spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./db/yuq;AUTO_SERVER=TRUE
    username: yuq
    password: yuq
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

yuq:
  art:
    qq:
    password:
    master: 734669014
